# Generated by Django 4.2.7 on 2023-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_insight_anxietyindicator_remove_insight_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="coping_strategies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="dietary_habits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="emotion_triggers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="emotions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="goals_aspirations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="gratitude_mentions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="key_mental_health_themes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="moods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="negative_behaviors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="physical_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="positive_behaviors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="self_reflection_insights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="sentiment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="sleep_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="social_interactions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="stress_signals",
            field=models.TextField(blank=True, null=True),
        ),
    ]
