# Generated by Django 4.2.7 on 2024-01-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_moodentry_user_delete_emotion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionabletask",
            name="improvement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actionable_tasks",
                to="myapp.userimprovement",
            ),
        ),
    ]
