# Generated by Django 4.2.7 on 2024-03-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0018_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimprovement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="userimprovement",
            unique_together={("user", "date")},
        ),
    ]
