# Generated by Django 4.2.7 on 2024-03-05 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_userimprovement_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="preferred_message_styles",
            new_name="preferred_style",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="preferred_message_types",
            new_name="preferred_type",
        ),
    ]
