# Generated by Django 4.2.7 on 2024-03-06 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "myapp",
            "0020_rename_preferred_message_styles_usersettings_preferred_style_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userimprovement",
            unique_together={("user", "timestamp")},
        ),
    ]
