# Generated by Django 4.2.7 on 2024-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_alter_userimprovement_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="is_peronsalized_complete",
            field=models.BooleanField(default=False),
        ),
    ]
