# Generated by Django 4.2.7 on 2024-04-16 19:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "myapp",
            "0027_rename_is_peronsalized_complete_userpreferences_is_personalised",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="content",
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
