# Generated by Django 4.2.7 on 2024-04-16 19:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0028_alter_journalentry_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="content",
            field=django_cryptography.fields.encrypt(
                models.TextField(default=None, null=True)
            ),
        ),
    ]
