# Generated by Django 4.2.7 on 2023-11-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_insight_anxietyindicator_insight_keywords_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insight",
            name="anxietyIndicator",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="entry",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="sentimentScore",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="stressLevel",
        ),
        migrations.AddField(
            model_name="insight",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to="myapp.user",
            ),
        ),
    ]
