# Generated by Django 4.2.7 on 2023-11-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_insight_coping_strategies_insight_dietary_habits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insight",
            name="coping_strategies",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="dietary_habits",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="emotion_triggers",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="emotions",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="goals_aspirations",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="gratitude_mentions",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="insightText",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="key_mental_health_themes",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="negative_behaviors",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="physical_activities",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="positive_behaviors",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="self_reflection_insights",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="sleep_details",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="social_interactions",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="stress_signals",
        ),
        migrations.AddField(
            model_name="insight",
            name="key_themes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
