# Generated by Django 4.2.7 on 2023-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_insight_coping_strategies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="moodRating",
            field=models.IntegerField(default=0),
        ),
    ]
