# Generated by Django 4.2.7 on 2024-01-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_insight_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionableInsight",
            fields=[
                ("insightId", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(help_text="The actionable insight text.")),
                (
                    "isCompleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has completed this action.",
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        default=0,
                        help_text="Relevance score of the insight based on user's current context.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actionable_insights",
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "relevance"],
            },
        ),
    ]
