# Generated by Django 4.2.7 on 2024-01-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_actionableinsight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionableTask",
            fields=[
                ("taskId", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(help_text="The actionable task text.")),
                (
                    "isCompleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has completed this action.",
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        default=0,
                        help_text="Relevance score of the insight based on user's current context.",
                    ),
                ),
                (
                    "improvement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actionable_tasks",
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "ordering": ["relevance"],
            },
        ),
        migrations.RenameField(
            model_name="userimprovement",
            old_name="tipId",
            new_name="improvementId",
        ),
        migrations.RemoveField(
            model_name="userimprovement",
            name="isActive",
        ),
        migrations.RemoveField(
            model_name="userimprovement",
            name="tipText",
        ),
        migrations.RemoveField(
            model_name="userimprovement",
            name="tipType",
        ),
        migrations.AddField(
            model_name="userimprovement",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userimprovement",
            name="message_of_the_day",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userimprovement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="improvement_plans",
                to="myapp.user",
            ),
        ),
        migrations.DeleteModel(
            name="ActionableInsight",
        ),
    ]
