# Generated by Django 4.2.7 on 2024-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_actionabletask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodentry",
            name="user",
        ),
        migrations.DeleteModel(
            name="Emotion",
        ),
        migrations.DeleteModel(
            name="MoodEntry",
        ),
    ]
