# Generated by Django 4.2.7 on 2024-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_alter_actionabletask_improvement"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionabletask",
            name="explanation",
            field=models.TextField(null=True),
        ),
    ]
