# Generated by Django 4.2.7 on 2024-01-25 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_actionabletask_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionabletask",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
