# Generated by Django 4.2.7 on 2024-02-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0016_alter_journalentry_user_alter_userimprovement_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionabletask",
            options={"ordering": ["inProgress"]},
        ),
        migrations.RemoveField(
            model_name="actionabletask",
            name="relevance",
        ),
        migrations.AddField(
            model_name="actionabletask",
            name="inProgress",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
