# Generated by Django 4.2.7 on 2024-02-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0017_alter_actionabletask_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_message_types",
                    models.CharField(
                        choices=[
                            ("poem", "Poem"),
                            ("story", "Story"),
                            ("quote", "Quote"),
                            ("motivation", "Motivation"),
                        ],
                        default="motivation",
                        max_length=50,
                    ),
                ),
                (
                    "preferred_message_styles",
                    models.CharField(
                        choices=[
                            ("stoic", "Stoic"),
                            ("funny", "Funny"),
                            ("deep", "Deep"),
                            ("insightful", "Insightful"),
                        ],
                        default="insightful",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
