# Generated by Django 4.2.7 on 2024-03-11 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_userpreferences_delete_usersettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreferences",
            old_name="is_peronsalized_complete",
            new_name="is_personalised",
        ),
    ]
