# Generated by Django 4.2.7 on 2024-03-06 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0023_alter_userimprovement_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userimprovement",
            unique_together={("user", "date")},
        ),
    ]
